[package]
name = "realm-magement-moniter"
version = "0.0.1"
authors = ["CCA Contributors"]
edition = "2018"

[[bin]]
name = "rmm"
path = "src/main.rs"

[dependencies]

[build-dependencies]
cc = "1.0"

[features]
