[package]
name = "realm-management-monitor"
version = "0.0.1"
authors = ["CCA Contributors"]
edition = "2018"

[[bin]]
name = "rmm"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[dependencies]
linked_list_allocator = "0.9.1"
lock_api = "=0.4.3"

[build-dependencies]
cc = "1.0"

[features]
