name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [ code-default ]
    container: art.sec.samsung.net/docker-remote/rust:latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install sudo
      run: |
        apt update && apt install sudo

    - name: Run scripts/init.sh
      run: ./scripts/init.sh

    - name: Run scripts/build.sh
      run: ./scripts/build.sh

    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          out/*.bin  
